# Generated by Django 4.0.4 on 2022-07-21 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('short_info', models.CharField(max_length=400)),
                ('posted_by', models.CharField(max_length=400)),
                ('date', models.DateField(auto_now_add=True)),
                ('main_img', models.ImageField(upload_to='')),
                ('text', models.TextField()),
                ('title2', models.CharField(blank=True, max_length=400, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('img2', models.ImageField(blank=True, null=True, upload_to='')),
                ('img2alt', models.CharField(blank=True, max_length=400, null=True)),
                ('title3', models.CharField(blank=True, max_length=400, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('img3', models.ImageField(blank=True, null=True, upload_to='')),
                ('img3alt', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
