# Generated by Django 4.0.4 on 2022-07-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageHeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True)),
                ('backgroundimg', models.ImageField(blank=True, null=True, upload_to='')),
                ('head_line', models.CharField(blank=True, max_length=200, null=True)),
                ('p', models.CharField(blank=True, max_length=200, null=True)),
                ('backgroundimg2', models.ImageField(blank=True, null=True, upload_to='')),
                ('head_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('p2', models.CharField(blank=True, max_length=200, null=True)),
                ('backgroundimg3', models.ImageField(blank=True, null=True, upload_to='')),
                ('head_line3', models.CharField(blank=True, max_length=200, null=True)),
                ('p3', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopPageHeadLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('head_line', models.CharField(blank=True, max_length=200, null=True)),
                ('p', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
